ITEMS_DICT = {
    'Item 1.01': 'Item 1.01',
    'Entry into a Material Definitive Agreement': 'Item 1.01',
    'Item 1.02': 'Item 1.02',
    'Termination of a Material Definitive Agreement': 'Item 1.02',
    'Item 1.03': 'Item 1.03',
    'Bankruptcy or Receivership': 'Item 1.03',
    'Item 1.04': 'Item 1.04',
    'Mine Safety - Reporting of Shutdowns and Patterns of Violations': 'Item 1.04',
    'Item 2.01': 'Item 2.01',
    'Completion of Acquisition or Disposition of Assets': 'Item 2.01',
    'Item 2.02': 'Item 2.02',
    'Results of Operations and Financial Condition': 'Item 2.02',
    'Item 2.03': 'Item 2.03',
    'Creation of a Direct Financial Obligation': 'Item 2.03',
    'Obligation under an Off-Balance Sheet Arrangement of a Registrant': 'Item 2.03',
    'Item 2.04': 'Item 2.04',
    'Triggering Events That Accelerate or Increase a Direct Financial Obligation or an Obligation under an Off-Balance Sheet Arrangement': 'Item 2.04',
    'Item 2.05': 'Item 2.05',
    'Costs Associated with Exit or Disposal Activities': 'Item 2.05',
    'Item 2.06': 'Item 2.06',
    'Material Impairments': 'Item 2.06',
    'Item 3.01': 'Item 3.01',
    'Notice of Delisting or Failure to Satisfy a Continued Listing Rule or Standard; Transfer of Listing': 'Item 3.01',
    'Item 3.02': 'Item 3.02',
    'Unregistered Sales of Equity Securities': 'Item 3.02',
    'Item 3.03': 'Item 3.03',
    'Material Modification to Rights of Security Holders': 'Item 3.03',
    'Item 4.01': 'Item 4.01',
    "Changes in Registrant's Certifying Accountant": 'Item 4.01',
    'Item 4.02': 'Item 4.02',
    'Non-Reliance on Previously Issued Financial Statements or a Related Audit Report or Completed Interim Review': 'Item 4.02',
    'Item 5.01': 'Item 5.01',
    'Changes in Control of Registrant': 'Item 5.01',
    'Item 5.02': 'Item 5.02',
    'Departure of Directors or Certain Officers': 'Item 5.02',
    'Election of Directors': 'Item 5.02',
    'Appointment of Certain Officers': 'Item 5.02',
    'Compensatory Arrangements of Certain Officers': 'Item 5.02',
    'Item 5.03': 'Item 5.03',
    'Amendments to Articles of Incorporation or Bylaws': 'Item 5.03',
    'Change in Fiscal Year': 'Item 5.03',
    'Item 5.04': 'Item 5.04',
    "Temporary Suspension of Trading Under Registrant's Employee Benefit Plans": 'Item 5.04',
    'Item 5.05': 'Item 5.05',
    "Amendment to Registrant's Code of Ethics, or Waiver of a Provision of the Code of Ethics": 'Item 5.05',
    'Item 5.06': 'Item 5.06',
    'Change in Shell Company Status': 'Item 5.06',
    'Item 5.07': 'Item 5.07',
    'Submission of Matters to a Vote of Security Holders': 'Item 5.07',
    'Item 5.08': 'Item 5.08',
    'Shareholder Director Nominations': 'Item 5.08',
    'Item 6.01': 'Item 6.01',
    'ABS Informational and Computational Material': 'Item 6.01',
    'Item 6.02': 'Item 6.02',
    'Change of Servicer or Trustee': 'Item 6.02',
    'Item 6.03': 'Item 6.03',
    'Change in Credit Enhancement or Other External Support': 'Item 6.03',
    'Item 6.04': 'Item 6.04',
    'Failure to Make a Required Distribution': 'Item 6.04',
    'Item 6.05': 'Item 6.05',
    'Securities Act Updating Disclosure': 'Item 6.05',
    'Item 7.01': 'Item 7.01',
    'Regulation FD Disclosure': 'Item 7.01',
    'Item 8.01': 'Item 8.01',
    'Other Events': 'Item 8.01',
    'Item 9.01': 'Item 9.01',
    'Financial Statements and Exhibits': 'Item 9.01'
}

ITEMS_LIST = sorted(list(set(ITEMS_DICT.values())))
