
SNP_TICKERS = ['AAPL', 'XOM', 'GE', 'CVX', 'MSFT', 'IBM', 'T', 'GOOG', 'PG', 'JNJ', 'PFE', 'WFC', 'BRK.B', 'JPM', 'PM',
               'KO', 'MRK', 'VZ', 'WMT', 'ORCL', 'INTC', 'PEP', 'ABT', 'QCOM', 'CSCO', 'SLB', 'C', 'CMCSA', 'BAC',
               'DIS', 'MCD', 'AMZN', 'HD', 'KFT', 'V', 'OXY', 'COP', 'MO', 'UTX', 'USB', 'AMGN', 'CVS', 'MMM', 'EMC',
               'UNH', 'BMY', 'UNP', 'CAT', 'EBAY', 'AXP', 'UPS', 'GS', 'ESRX', 'GILD', 'NWSA', 'MON', 'MA', 'LLY', 'CL',
               'BA', 'DD', 'HON', 'SPG', 'DUK', 'ACN', 'MDT', 'COST', 'TWX', 'TGT', 'SO', 'SBUX', 'AIG', 'F', 'FCX',
               'MET', 'BIIB', 'EMR', 'APC', 'NKE', 'DOW', 'LOW', 'NOV', 'KMB', 'APA', 'HPQ', 'PNC', 'COF', 'BAX', 'TJX',
               'CELG', 'DTV', 'DE', 'DHR', 'TXN', 'HAL', 'WAG', 'PX', 'PCLN', 'EXC', 'D', 'EOG', 'YUM', 'NEE', 'TWC',
               'PSX', 'COV', 'ADP', 'AMT', 'AGN', 'NEM', 'BK', 'TRV', 'TYC', 'GIS', 'ITW', 'ACE', 'PRU', 'VIAB', 'CTL',
               'LMT', 'FDX', 'PCP', 'BBT', 'MS', 'BLK', 'DVN', 'AFL', 'ALXN', 'GD', 'WMB', 'CBS', 'CSX', 'TMO', 'AEP',
               'CTSH', 'MRO', 'DFS', 'NSC', 'MCK', 'CB', 'KMI', 'STT', 'PSA', 'BHI', 'ISRG', 'GLW', 'CRM', 'ALL', 'SE',
               'HCP', 'RTN', 'WLP', 'CCI', 'JCI', 'MPC', 'MMC', 'FE', 'VTR', 'SYY', 'PCG', 'HNZ', 'ADM', 'BRCM', 'ED',
               'PPG', 'CME', 'LYB', 'APD', 'VLO', 'EQR', 'BEN', 'ECL', 'PPL', 'AON', 'WFM', 'BXP', 'YHOO', 'S', 'NBL',
               'NOC', 'CMI', 'CCL', 'PEG', 'INTU', 'PLD', 'SYK', 'TROW', 'COH', 'ADBE', 'HES', 'ETN', 'MOS', 'IP',
               'BDX', 'MHP', 'STI', 'LO', 'M', 'MJN', 'EIX', 'EL', 'DISCA', 'HCN', 'BBBY', 'TEL', 'SRE', 'MSI', 'ROST',
               'DELL', 'CTXS', 'FITB', 'RAI', 'PCAR', 'WY', 'SCHW', 'VFC', 'WM', 'CF', 'AZO', 'AMAT', 'CAM', 'VNO',
               'OMC', 'CI', 'XEL', 'A', 'CAH', 'AET', 'STJ', 'AVB', 'L', 'IR', 'PXD', 'KR', 'SWK', 'K', 'TDC', 'SHW',
               'ESV', 'SYMC', 'PH', 'GWW', 'EW', 'ETR', 'NUE', 'SWN', 'MAT', 'CBE', 'NU', 'AMP', 'NTAP', 'ZMH', 'LTD',
               'ADI', 'PGR', 'HST', 'FAST', 'MTB', 'HOT', 'RRC', 'HUM', 'CERN', 'CAG', 'IVZ', 'DLTR', 'KSS', 'FTI',
               'RHT', 'WU', 'STX', 'DOV', 'ALTR', 'WPI', 'HSY', 'ROP', 'PAYX', 'GPS', 'SNDK', 'DTE', 'PRGO', 'RF',
               'NTRS', 'DGX', 'CMG', 'FISV', 'ORLY', 'MUR', 'OKE', 'MYL', 'BF.B', 'MAR', 'ROK', 'CHK', 'ABC', 'ICE',
               'HOG', 'XRX', 'APH', 'GPC', 'CHRW', 'SJM', 'AA', 'COG', 'FLR', 'DPS', 'CLX', 'RL', 'WYNN', 'BEAM', 'CNP',
               'NE', 'JNPR', 'LH', 'EQT', 'CA', 'DVA', 'XLNX', 'EMN', 'SIAL', 'WEC', 'CCE', 'WDC', 'LIFE', 'MCO', 'HIG',
               'JWN', 'FRX', 'MNST', 'FFIV', 'NVDA', 'KIM', 'KEY', 'RSG', 'MKC', 'BCR', 'BSX', 'KLAC', 'AEE', 'BWA',
               'SPLS', 'FIS', 'SRCL', 'EXPD', 'COL', 'VRSN', 'FMC', 'ADSK', 'PFG', 'WYN', 'SLM', 'PLL', 'TIF', 'TXT',
               'XL', 'LLTC', 'WAT', 'NI', 'DRI', 'PCL', 'TAP', 'LLL', 'AVP', 'CNX', 'AES', 'AKAM', 'LNC', 'VAR', 'BLL',
               'FLS', 'LUV', 'KMX', 'FDO', 'WHR', 'MCHP', 'SCG', 'DNR', 'CFN', 'CPB', 'CMS', 'VMC', 'MU', 'BMC', 'NYX',
               'CMA', 'BTU', 'WIN', 'JOY', 'HBAN', 'TSO', 'HRS', 'LRCX', 'PNW', 'DHI', 'ARG', 'LEN', 'QEP', 'EFX',
               'CVH', 'CLF', 'CBG', 'CINF', 'NWL', 'HSP', 'EXPE', 'XRAY', 'UNM', 'MAS', 'MWV', 'SNI', 'PWR', 'JEC',
               'PHM', 'IRM', 'HP', 'CSC', 'SUN', 'TMK', 'FTR', 'NRG', 'IPG', 'IFF', 'GAS', 'STZ', 'HRB', 'XYL', 'TSN',
               'FOSL', 'DO', 'BBY', 'LUK', 'CTAS', 'HAS', 'POM', 'PBCT', 'NFX', 'RDC', 'SNA', 'GCI', 'URBN', 'NBR',
               'TEG', 'EA', 'HRL', 'SWY', 'LSI', 'TSS', 'ZION', 'HCBK', 'AIV', 'RHI', 'PCS', 'MOLX', 'TE', 'TRIP',
               'DNB', 'LEG', 'JBL', 'IGT', 'JCP', 'CVC', 'ATI', 'SAI', 'PKI', 'WPX', 'BMS', 'AVY', 'HAR', 'OI', 'AIZ',
               'NFLX', 'DF', 'FLIR', 'GT', 'LM', 'APOL', 'PDCO', 'JDSU', 'ANF', 'PBI', 'NDAQ', 'X', 'SEE', 'TER', 'THC',
               'GME', 'GNW', 'FHN', 'ETFC', 'AMD', 'R', 'FII', 'RRD', 'BIG', 'AN', 'WPO', 'LXK', 'ANR', 'FSLR', 'DV',
               'TIE']

ALL_TICKERS = ['A', 'AA', 'AAN', 'AAON', 'AAP', 'AAPL', 'ABAX', 'ABC', 'ABFS', 'ABM', 'ABT', 'ACAT', 'ACC', 'ACE',
               'ACI',
               'ACIW', 'ACM', 'ACN', 'ACO', 'ACXM', 'ADBE', 'ADI', 'ADM', 'ADP', 'ADS', 'ADSK', 'ADTN', 'ADVS', 'AEE',
               'AEGN', 'AEIS', 'AEO', 'AEP', 'AES', 'AET', 'AF', 'AFAM', 'AFFX', 'AFG', 'AFL', 'AGCO', 'AGN', 'AGP',
               'AGYS',
               'AHL', 'AHS', 'AIG', 'AINV', 'AIR', 'AIRM', 'AIT', 'AIV', 'AIZ', 'AJG', 'AKAM', 'AKR', 'AKRX', 'AKS',
               'ALB',
               'ALE', 'ALEX', 'ALGN', 'ALGT', 'ALK', 'ALL', 'ALOG', 'ALTR', 'ALXN', 'AM', 'AMAT', 'AMCX', 'AMD', 'AME',
               'AMED', 'AMG', 'AMGN', 'AMP', 'AMSF', 'AMSG', 'AMT', 'AMZN', 'AN', 'ANDE', 'ANF', 'ANN', 'ANR', 'ANSS',
               'AOL', 'AON', 'AOS', 'APA', 'APC', 'APD', 'APEI', 'APH', 'APOG', 'APOL', 'ARB', 'ARE', 'AREX', 'ARG',
               'ARO',
               'ARQL', 'ARRS', 'ARW', 'ASBC', 'ASEI', 'ASGN', 'ASH', 'ASNA', 'ASTE', 'ATI', 'ATK', 'ATMI', 'ATML',
               'ATNI',
               'ATO', 'ATR', 'ATU', 'ATW', 'AVA', 'AVAV', 'AVB', 'AVD', 'AVID', 'AVP', 'AVT', 'AVY', 'AWR', 'AXE',
               'AXP',
               'AYI', 'AZO', 'AZZ', 'B', 'BA', 'BABY', 'BAC', 'BAS', 'BAX', 'BBBY', 'BBG', 'BBOX', 'BBT', 'BBY', 'BC',
               'BCO', 'BCOR', 'BCPC', 'BCR', 'BDC', 'BDX', 'BEAM', 'BEAV', 'BELFB', 'BEN', 'BFS', 'BGC', 'BGFV', 'BGG',
               'BGS', 'BH', 'BHE', 'BHI', 'BID', 'BIG', 'BIIB', 'BJRI', 'BK', 'BKE', 'BKH', 'BKI', 'BKMU', 'BKS', 'BLK',
               'BLKB', 'BLL', 'BMC', 'BMI', 'BMR', 'BMS', 'BMY', 'BOBE', 'BOH', 'BPFH', 'BR', 'BRC', 'BRCM', 'BRKL',
               'BRKS',
               'BRLI', 'BRO', 'BRS', 'BSX', 'BTH', 'BTU', 'BWA', 'BWLD', 'BWS', 'BXP', 'BXS', 'BYD', 'BYI', 'C', 'CA',
               'CAB', 'CACI', 'CAG', 'CAH', 'CAKE', 'CALM', 'CAM', 'CAS', 'CASC', 'CASY', 'CAT', 'CATM', 'CATO', 'CATY',
               'CB', 'CBB', 'CBE', 'CBEY', 'CBG', 'CBK', 'CBM', 'CBOE', 'CBR', 'CBRL', 'CBS', 'CBSH', 'CBST', 'CBT',
               'CBU',
               'CCC', 'CCE', 'CCI', 'CCL', 'CCMP', 'CCRN', 'CDI', 'CDNS', 'CDR', 'CEB', 'CEC', 'CECO', 'CELG', 'CELL',
               'CENX', 'CERN', 'CEVA', 'CF', 'CFN', 'CFR', 'CGNX', 'CGX', 'CHCO', 'CHD', 'CHE', 'CHG', 'CHK', 'CHRW',
               'CHS',
               'CI', 'CIEN', 'CINF', 'CIR', 'CKH', 'CKP', 'CL', 'CLC', 'CLD', 'CLF', 'CLGX', 'CLH', 'CLI', 'CLMS',
               'CLP',
               'CLW', 'CLX', 'CMA', 'CMC', 'CMCSA', 'CME', 'CMG', 'CMI', 'CMN', 'CMP', 'CMS', 'CMTL', 'CNC', 'CNK',
               'CNL',
               'CNMD', 'CNP', 'CNQR', 'CNW', 'CNX', 'COCO', 'COF', 'COG', 'COH', 'COHU', 'COL', 'COLB', 'COO', 'COP',
               'COST', 'COV', 'CPB', 'CPLA', 'CPRT', 'CPSI', 'CPT', 'CPWR', 'CR', 'CRDN', 'CREE', 'CRI', 'CRK', 'CRL',
               'CRM', 'CROX', 'CRR', 'CRS', 'CRUS', 'CRVL', 'CRY', 'CSC', 'CSCO', 'CSGS', 'CSH', 'CSL', 'CSTR', 'CSX',
               'CTAS', 'CTL', 'CTS', 'CTSH', 'CTXS', 'CUB', 'CUZ', 'CVBF', 'CVC', 'CVD', 'CVG', 'CVGW', 'CVH', 'CVLT',
               'CVS', 'CVX', 'CW', 'CWTR', 'CXW', 'CY', 'CYBX', 'CYH', 'CYMI', 'CYN', 'CYT', 'D', 'DAKT', 'DAR', 'DBD',
               'DCI', 'DCOM', 'DD', 'DDD', 'DE', 'DECK', 'DEL', 'DELL', 'DF', 'DFS', 'DGII', 'DGIT', 'DGX', 'DHI',
               'DHR',
               'DHX', 'DIN', 'DIOD', 'DIS', 'DISCA', 'DKS', 'DLTR', 'DLX', 'DM', 'DMND', 'DNB', 'DNR', 'DO', 'DOV',
               'DOW',
               'DPS', 'DRC', 'DRE', 'DRH', 'DRI', 'DRIV', 'DRQ', 'DSPG', 'DTE', 'DTSI', 'DTV', 'DUK', 'DV', 'DVA',
               'DVN',
               'DW', 'DWA', 'DY', 'EA', 'EAT', 'EBAY', 'EBIX', 'EBS', 'ECL', 'ECPG', 'ED', 'EE', 'EFX', 'EGL', 'EGN',
               'EGP',
               'EHTH', 'EIG', 'EIX', 'EL', 'ELY', 'EMC', 'EME', 'EMN', 'EMR', 'ENDP', 'ENR', 'ENS', 'ENSG', 'ENTR',
               'ENZ',
               'EOG', 'EPAY', 'EPIQ', 'EPR', 'EQIX', 'EQR', 'EQT', 'EQY', 'ESE', 'ESI', 'ESIO', 'ESL', 'ESRX', 'ESS',
               'ESV',
               'ETFC', 'ETH', 'ETN', 'ETR', 'EV', 'EW', 'EWBC', 'EXAR', 'EXC', 'EXH', 'EXLS', 'EXP', 'EXPD', 'EXPE',
               'EXPO',
               'EXR', 'EZPW', 'F', 'FAF', 'FARO', 'FAST', 'FBHS', 'FBP', 'FCF', 'FCFS', 'FCN', 'FCS', 'FCX', 'FDO',
               'FDS',
               'FDX', 'FE', 'FEIC', 'FELE', 'FFBC', 'FFIN', 'FFIV', 'FHN', 'FICO', 'FII', 'FINL', 'FIRE', 'FIS', 'FISV',
               'FITB', 'FIX', 'FL', 'FLIR', 'FLO', 'FLR', 'FLS', 'FMBI', 'FMC', 'FMER', 'FNB', 'FNF', 'FNFG', 'FNGN',
               'FNP',
               'FOR', 'FORR', 'FOSL', 'FRED', 'FRT', 'FRX', 'FSLR', 'FSP', 'FST', 'FTI', 'FTR', 'FUL', 'FULT', 'FWRD',
               'GAS', 'GB', 'GBCI', 'GCI', 'GCO', 'GD', 'GDI', 'GE', 'GEF', 'GEO', 'GES', 'GFF', 'GGG', 'GHL', 'GIFI',
               'GILD', 'GIS', 'GLW', 'GMCR', 'GME', 'GMT', 'GNCMA', 'GNTX', 'GNW', 'GOOG', 'GPC', 'GPI', 'GPN', 'GPOR',
               'GPS', 'GS', 'GSM', 'GT', 'GTAT', 'GTIV', 'GTY', 'GVA', 'GWW', 'GXP', 'GY', 'HAE', 'HAFC', 'HAIN', 'HAL',
               'HAR', 'HAS', 'HAYN', 'HBAN', 'HBHC', 'HBI', 'HCBK', 'HCC', 'HCN', 'HCP', 'HCSG', 'HD', 'HE', 'HES',
               'HF',
               'HFC', 'HGR', 'HHS', 'HI', 'HIBB', 'HIG', 'HII', 'HITK', 'HITT', 'HIW', 'HLIT', 'HLX', 'HMA', 'HME',
               'HMN',
               'HMSY', 'HNI', 'HNT', 'HNZ', 'HOG', 'HOLX', 'HOMB', 'HON', 'HOS', 'HOT', 'HOTT', 'HP', 'HPQ', 'HPT',
               'HPY',
               'HR', 'HRB', 'HRC', 'HRL', 'HRS', 'HSC', 'HSH', 'HSIC', 'HSII', 'HSNI', 'HSP', 'HST', 'HSTM', 'HSY',
               'HTLD',
               'HTSI', 'HUBG', 'HUM', 'HVT', 'HW', 'HWAY', 'HWKN', 'HZO', 'IART', 'IBKR', 'IBM', 'IBOC', 'ICE', 'ICON',
               'ICUI', 'IDA', 'IDTI', 'IDXX', 'IEX', 'IFF', 'IFSIA', 'IGT', 'IGTE', 'IILG', 'IIVI', 'IM', 'IN', 'INDB',
               'INFA', 'INGR', 'ININ', 'INT', 'INTC', 'INTU', 'IO', 'IP', 'IPAR', 'IPCC', 'IPCM', 'IPG', 'IPHS', 'IPI',
               'IR', 'IRBT', 'IRC', 'IRF', 'IRM', 'ISCA', 'ISIL', 'ISRG', 'IT', 'ITG', 'ITRI', 'ITT', 'ITW', 'IVAC',
               'IVC',
               'IVZ', 'JACK', 'JAH', 'JAKK', 'JBHT', 'JBL', 'JBLU', 'JBT', 'JCI', 'JCOM', 'JCP', 'JDAS', 'JDSU', 'JEC',
               'JEF', 'JJSF', 'JKHY', 'JLL', 'JNJ', 'JNPR', 'JNS', 'JOSB', 'JOY', 'JPM', 'JWN', 'K', 'KALU', 'KAMN',
               'KBH',
               'KBR', 'KDN', 'KELYA', 'KEX', 'KEY', 'KFY', 'KIM', 'KIRK', 'KLAC', 'KLIC', 'KMB', 'KMI', 'KMPR', 'KMT',
               'KMX', 'KND', 'KNX', 'KO', 'KOP', 'KOPN', 'KR', 'KRA', 'KRC', 'KRG', 'KS', 'KSS', 'KSU', 'KSWS', 'KWK',
               'KWR', 'L', 'LAD', 'LAMR', 'LANC', 'LAWS', 'LDL', 'LDR', 'LECO', 'LEG', 'LEN', 'LFUS', 'LG', 'LH',
               'LHCG',
               'LHO', 'LIFE', 'LII', 'LINC', 'LKQ', 'LL', 'LLL', 'LLTC', 'LLY', 'LM', 'LMNX', 'LMOS', 'LMT', 'LNC',
               'LNCE',
               'LNN', 'LNT', 'LO', 'LOGM', 'LOW', 'LPNT', 'LPS', 'LPSN', 'LPX', 'LQDT', 'LRCX', 'LRY', 'LSI', 'LSTR',
               'LTC',
               'LTD', 'LTM', 'LUFK', 'LUK', 'LUV', 'LXK', 'LXP', 'LXU', 'LYV', 'LZB', 'M', 'MA', 'MAA', 'MAC', 'MAN',
               'MANH', 'MANT', 'MAR', 'MAS', 'MASI', 'MAT', 'MATW', 'MATX', 'MCD', 'MCF', 'MCHP', 'MCK', 'MCO', 'MCRI',
               'MCRL', 'MCRS', 'MCS', 'MCY', 'MD', 'MDC', 'MDCO', 'MDP', 'MDRX', 'MDSO', 'MDT', 'MDU', 'MEAS', 'MED',
               'MEI',
               'MENT', 'MET', 'MFB', 'MGAM', 'MGLN', 'MHK', 'MHO', 'MIG', 'MINI', 'MJN', 'MKC', 'MKSI', 'MLHR', 'MLI',
               'MLM', 'MMC', 'MMM', 'MMS', 'MMSI', 'MNRO', 'MNST', 'MNTA', 'MO', 'MOH', 'MOLX', 'MON', 'MOS', 'MOV',
               'MPC',
               'MPW', 'MPWR', 'MRCY', 'MRK', 'MRO', 'MRX', 'MS', 'MSA', 'MSCC', 'MSCI', 'MSFT', 'MSI', 'MSM', 'MSTR',
               'MTB',
               'MTD', 'MTH', 'MTRN', 'MTRX', 'MTSC', 'MTX', 'MU', 'MUR', 'MW', 'MWIV', 'MWV', 'MWW', 'MYE', 'MYL',
               'NAFC',
               'NANO', 'NATI', 'NAVG', 'NBL', 'NBR', 'NBTB', 'NCI', 'NCIT', 'NCR', 'NCS', 'NDAQ', 'NDSN', 'NE', 'NEE',
               'NEM', 'NEOG', 'NEU', 'NEWP', 'NFG', 'NFLX', 'NFP', 'NFX', 'NI', 'NILE', 'NJR', 'NKE', 'NNN', 'NOC',
               'NOV',
               'NP', 'NPBC', 'NPK', 'NPO', 'NRG', 'NSC', 'NSIT', 'NSP', 'NSR', 'NTAP', 'NTCT', 'NTGR', 'NTLS', 'NTRI',
               'NTRS', 'NU', 'NUE', 'NUVA', 'NVDA', 'NVE', 'NVR', 'NVTL', 'NWBI', 'NWE', 'NWL', 'NWN', 'NWSA', 'NX',
               'NYB',
               'NYT', 'NYX', 'O', 'OCR', 'ODFL', 'ODP', 'OFC', 'OGE', 'OHI', 'OI', 'OII', 'OIS', 'OKE', 'OLN', 'OMC',
               'OMCL', 'OMG', 'OMI', 'OMX', 'ONB', 'ONE', 'OPEN', 'OPLK', 'OPNT', 'ORB', 'ORCL', 'ORI', 'ORIT', 'ORLY',
               'ORN', 'OSG', 'OSIS', 'OSK', 'OXM', 'OXY', 'OZRK', 'PACW', 'PAY', 'PAYX', 'PB', 'PBCT', 'PBH', 'PBI',
               'PBY',
               'PCAR', 'PCG', 'PCH', 'PCL', 'PCLN', 'PCP', 'PCTI', 'PDCE', 'PDCO', 'PEET', 'PEG', 'PEI', 'PEP', 'PERY',
               'PES', 'PETM', 'PETS', 'PFE', 'PFG', 'PFS', 'PG', 'PGR', 'PH', 'PHM', 'PII', 'PJC', 'PKE', 'PKG', 'PKI',
               'PKY', 'PL', 'PLCE', 'PLCM', 'PLD', 'PLFE', 'PLL', 'PLT', 'PLXS', 'PM', 'PMC', 'PMTC', 'PMTI', 'PNC',
               'PNFP',
               'PNK', 'PNM', 'PNR', 'PNRA', 'PNW', 'PNY', 'POL', 'POM', 'POOL', 'POST', 'POWI', 'POWL', 'PPG', 'PPS',
               'PQ',
               'PRA', 'PRAA', 'PRFT', 'PRGO', 'PRGS', 'PRU', 'PRX', 'PRXL', 'PSA', 'PSB', 'PSEC', 'PSEM', 'PSS', 'PSSI',
               'PSX', 'PTEN', 'PULS', 'PVA', 'PVH', 'PVTB', 'PWR', 'PX', 'PXD', 'PXP', 'PZZA', 'QCOM', 'QCOR', 'QEP',
               'QLGC', 'QNST', 'QSFT', 'QSII', 'R', 'RAH', 'RAI', 'RAX', 'RBC', 'RBCN', 'RBN', 'RCII', 'RDC', 'RE',
               'RECN',
               'REG', 'REGN', 'RF', 'RFMD', 'RGA', 'RGLD', 'RGR', 'RGS', 'RHI', 'RHT', 'RJF', 'RKT', 'RL', 'RLI', 'RMD',
               'ROCK', 'ROG', 'ROK', 'ROL', 'ROP', 'ROSE', 'ROST', 'ROVI', 'RPM', 'RRC', 'RRD', 'RRGB', 'RS', 'RSG',
               'RSH',
               'RSTI', 'RSYS', 'RT', 'RTEC', 'RTI', 'RTN', 'RUE', 'RUTH', 'RVBD', 'RYL', 'RYN', 'S', 'SAFM', 'SAFT',
               'SAH',
               'SAI', 'SAM', 'SBRA', 'SBUX', 'SCG', 'SCHL', 'SCHW', 'SCI', 'SCL', 'SCOR', 'SCSC', 'SCSS', 'SE', 'SEE',
               'SEIC', 'SENEA', 'SF', 'SFD', 'SFG', 'SFNC', 'SFY', 'SGMS', 'SGY', 'SHAW', 'SHFL', 'SHLM', 'SHOO', 'SHW',
               'SIAL', 'SIG', 'SIGI', 'SIGM', 'SIVB', 'SJI', 'SJM', 'SKS', 'SKT', 'SKX', 'SKYW', 'SLAB', 'SLB', 'SLG',
               'SLGN', 'SLH', 'SLM', 'SLXP', 'SM', 'SMA', 'SMCI', 'SMG', 'SMP', 'SMRT', 'SMTC', 'SNA', 'SNCR', 'SNDK',
               'SNH', 'SNI', 'SNPS', 'SNV', 'SNX', 'SO', 'SON', 'SONC', 'SPAR', 'SPF', 'SPG', 'SPLS', 'SPN', 'SPPI',
               'SPTN',
               'SPW', 'SRCL', 'SRDX', 'SRE', 'SSD', 'SSI', 'SSP', 'SSS', 'STBA', 'STC', 'STE', 'STI', 'STJ', 'STL',
               'STLD',
               'STMP', 'STR', 'STRA', 'STRI', 'STT', 'STX', 'STZ', 'SUN', 'SUP', 'SUPX', 'SUSQ', 'SVU', 'SWI', 'SWK',
               'SWKS', 'SWM', 'SWN', 'SWS', 'SWX', 'SWY', 'SXC', 'SXI', 'SXT', 'SYK', 'SYKE', 'SYMC', 'SYMM', 'SYNA',
               'SYY',
               'T', 'TAP', 'TBI', 'TCB', 'TCBI', 'TCO', 'TDC', 'TDS', 'TDW', 'TDY', 'TE', 'TECD', 'TECH', 'TEG', 'TEL',
               'TER', 'TEX', 'TFX', 'TG', 'TGI', 'TGT', 'THC', 'THG', 'THO', 'THOR', 'THS', 'TIBX', 'TIE', 'TIF', 'TJX',
               'TKR', 'TLAB', 'TMK', 'TMO', 'TMP', 'TNC', 'TOL', 'TPX', 'TQNT', 'TR', 'TRAK', 'TRIP', 'TRLG', 'TRMB',
               'TRMK', 'TRN', 'TROW', 'TRST', 'TRV', 'TSCO', 'TSN', 'TSO', 'TSRA', 'TSS', 'TTC', 'TTEC', 'TTEK', 'TTI',
               'TTMI', 'TTWO', 'TUES', 'TUP', 'TW', 'TWC', 'TWGP', 'TWTC', 'TWX', 'TXI', 'TXN', 'TXRH', 'TXT', 'TYC',
               'TYL',
               'TYPE', 'UA', 'UBA', 'UBSI', 'UCBI', 'UDR', 'UEIC', 'UFCS', 'UFPI', 'UFS', 'UGI', 'UHS', 'UHT', 'UIL',
               'UMBF', 'UMPQ', 'UNF', 'UNFI', 'UNH', 'UNM', 'UNP', 'UNS', 'UNT', 'UNTD', 'UPS', 'URBN', 'URI', 'URS',
               'USB',
               'USMO', 'USTR', 'UTEK', 'UTHR', 'UTI', 'UTIW', 'UTX', 'UVV', 'V', 'VAL', 'VAR', 'VCI', 'VCLK', 'VDSI',
               'VECO', 'VFC', 'VIAB', 'VICR', 'VIVO', 'VLO', 'VLTR', 'VLY', 'VMC', 'VMI', 'VNO', 'VOXX', 'VPFG', 'VPHM',
               'VRSN', 'VRTS', 'VRTU', 'VRTX', 'VSAT', 'VSH', 'VSI', 'VTR', 'VVC', 'VZ', 'WAB', 'WABC', 'WAFD', 'WAG',
               'WAT', 'WBS', 'WBSN', 'WCG', 'WCN', 'WDC', 'WDFC', 'WDR', 'WEC', 'WEN', 'WERN', 'WFC', 'WFM', 'WGL',
               'WGO',
               'WHR', 'WIBC', 'WIN', 'WIRE', 'WLP', 'WM', 'WMB', 'WMS', 'WMT', 'WOOF', 'WOR', 'WPO', 'WPP', 'WPX', 'WR',
               'WRB', 'WRC', 'WRI', 'WRLD', 'WSM', 'WSO', 'WST', 'WTFC', 'WTR', 'WTS', 'WU', 'WWD', 'WWW', 'WY', 'WYN',
               'WYNN', 'X', 'XEC', 'XEL', 'XL', 'XLNX', 'XLS', 'XOM', 'XOXO', 'XRAY', 'XRX', 'XYL', 'Y', 'YHOO', 'YUM',
               'ZBRA', 'ZEP', 'ZEUS', 'ZLC', 'ZMH', 'ZQK', 'ZUMZ']


TICKERS = sorted(list(set(SNP_TICKERS) & set(ALL_TICKERS)))
